export const gêneros = ['Sangue', 'Conhecimento', 'Morte', 'Energia'];
 
export const filmes = [
    
    { filme: "Zumbi de Sangue Espinhento", ano: "Ocultismo", gêneros: ["Sangue"], sinopse: "Os Zumbis de Sangue Espinhentos são criaturas letais com espinhos ósseos e braços alongados, tornando-os ainda mais perigosos.", imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUiF5m3PfW52DE9t2BI9A7VEzXQHpZkYQzYg&s", referência: "https://ordemparanormal.fandom.com/wiki/Zumbis_de_Sangue" },
    { filme: "Zumbi de Sangue Armadurado", ano: "Ocultismo", gêneros: ["Sangue"], sinopse: "O Zumbi de Sangue Decepado é uma criatura formada de um corpo mutilado, ligado por uma língua roxa, com garras afiadas e poderes de teletransporte.", imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ELvE7loVy7KDH2yYbh74fMfsAnz46hLEcQ&s", referência: "https://ordemparanormal.fandom.com/wiki/Zumbis_de_Sangue" }, 
    
    { filme: "Enraizados", ano: "Ocultismo, Santo Berço e Indústrias Panacea", gêneros: ["Morte"], sinopse: "Os Enraizados são cadáveres reanimados por raízes e Lodo da Morte, transformando-se em criaturas macabras e consumidas por dentro.", imagem: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmfQ7vDlJsF82oLl5KABSZr9G1Es_W4iUaiw&s", referência: "https://ordemparanormal.fandom.com/wiki/Enraizados" },
    { filme: "A Marionete", ano: "Ocultismo", gêneros: ["Morte"], sinopse: "A Marionete é uma criatura de Morte nascida do desespero de quem tenta reviver os mortos, servindo como distração e ameaça com sua presença inquietante.", imagem: "https://i.pinimg.com/236x/f1/c1/13/f1c113badebaf4affbf768111393475e.jpg", referência: "https://ordemparanormal.fandom.com/wiki/A_Marionete" },

    { filme: "vultos", ano: "Ocultismo e Santo Berço", gêneros: ["Conhecimento"], sinopse: "Os Vultos são criaturas de Conhecimento formadas pelo medo e paranoia de observadores em locais de membrana fraca, envoltos por uma neblina constante.", imagem: "https://i.pinimg.com/736x/10/91/8f/10918fce99b77d725ece453bc4bf6d93.jpg", referência: "https://ordemparanormal.fandom.com/wiki/Vultos" },
    { filme: "Existidos", ano: "Ocultismo e Escriptas", gêneros: ["Conhecimento"], sinopse: "Os Existidos são humanos que, ao compreenderem totalmente o Outro Lado, têm suas mentes desintegradas pela Verdade Impossível, renascendo como a manifestação poderosa chamada O Lembrado.", imagem: "https://i.pinimg.com/736x/9c/22/54/9c22544c153227b66ac105d6821203c9.jpg", referência: "https://ordemparanormal.fandom.com/wiki/Existidos_e_Lembrados" },

    { filme: "Perturbados de Energia", ano: "Ocultismo e Produção do Anfitrião", gêneros: ["Energia"], sinopse: "Os Perturbados de Energia são entidades formadas por almas enlouquecidas, cuja confusão extrema as impede de perceber sua própria morte.", imagem: "https://pbs.twimg.com/media/FgPr-ioWQAIZDGl.jpg:large", referência: "https://ordemparanormal.fandom.com/wiki/Perturbados_de_Energia" },
    { filme: "Tempestuoso", ano: "Ocultismo", gêneros: ["Energia"], sinopse: "O Tempestuoso é uma manifestação disforme de Energia gerada por turbilhões descontrolados em locais com a Membrana danificada, como usinas radioativas abandonadas.", imagem: "https://pbs.twimg.com/media/FuaYSRCWYAMlwXw.jpg", referência: "https://ordemparanormal.fandom.com/wiki/Tempestuoso" } ];
